export { default as DocsHeader } from './components/starlight/DocsHeader.astro'
export { default as EditLink } from './components/starlight/EditLink.astro'
export { default as Footer } from './components/starlight/Footer.astro'
export { default as PageFrame } from './components/starlight/PageFrame.astro'
export { default as Sidebar } from './components/starlight/Sidebar.astro'
export { default as SidebarSublist } from './components/starlight/SidebarSublist.astro'